import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { AuthProvider } from "@/context/auth.context";
import { cookies } from "next/headers";
import { serverApi } from "@/lib/api.server";
import type { User } from "@/types/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NextNext eCommerce",
  description: "Generated by create next app",
};

async function getUser(): Promise<User | null> {
  const cookieStore = await cookies();
  const token = cookieStore.get("Authentication");

  if (!token) return null;

  try {
    const { data } = await serverApi.get<User>("/auth/profile", {
      headers: { Cookie: `Authentication=${token.value}` },
    });

    return data;
  } catch (e) {
    return null;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider initialUser={user}>
          <Header />
          <main className="container">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
